// This file was generated by running command
//     scripts/build-shaders.sh shaders/constant.frag shaders/constant.vert
shaders = {
  'constant.frag':
  "#version 100 \n"+
  "precision mediump float; \n"+
  " \n"+
  "uniform vec4 color; \n"+
  " \n"+
  "void main() { \n"+
  "    gl_FragColor = color; \n"+
  "} \n"+
  "",
  'constant.vert':
  "#version 100 \n"+
  " \n"+
  "attribute vec2 pos; \n"+
  " \n"+
  "void main() { \n"+
  "    gl_Position = vec4(pos, 0, 1); \n"+
  "} \n"+
  ""
}
