// This file was generated by running command
//     scripts/build-shaders.sh shaders/blur.frag shaders/constant.frag shaders/constant.vert shaders/dither.frag shaders/effect.vert shaders/grayscale.frag
shaders = {
  'blur.frag':
  "#version 100 \n"+
  "precision mediump float; \n"+
  " \n"+
  "uniform sampler2D sampler; \n"+
  "uniform vec2 delta; \n"+
  "varying vec2 texCoord; \n"+
  " \n"+
  "void main() { \n"+
  "    const int KERNEL_SIZE = 3; \n"+
  "    float kernel[KERNEL_SIZE]; \n"+
  "    kernel[0] = 1.0; \n"+
  "    kernel[1] = 1.0; \n"+
  "    kernel[2] = 1.0; \n"+
  "    vec3 p = texture2D(sampler, texCoord).xyz * kernel[0]; \n"+
  "    for(int i=1; i<KERNEL_SIZE; i++) { \n"+
  "        p += texture2D(sampler, texCoord + delta*float(i)).xyz * kernel[i]; \n"+
  "        p += texture2D(sampler, texCoord - delta*float(i)).xyz * kernel[i]; \n"+
  "    } \n"+
  "    gl_FragColor = vec4(p / (float(KERNEL_SIZE)*2.0 - 1.0), 1.0); \n"+
  "} \n"+
  "",
  'constant.frag':
  "#version 100 \n"+
  "precision mediump float; \n"+
  " \n"+
  "uniform vec4 color; \n"+
  " \n"+
  "void main() { \n"+
  "    gl_FragColor = color; \n"+
  "} \n"+
  "",
  'constant.vert':
  "#version 100 \n"+
  " \n"+
  "uniform mat3 matrix; \n"+
  "attribute vec2 pos; \n"+
  " \n"+
  "void main() { \n"+
  "    gl_Position = vec4(matrix * vec3(pos, 1), 1); \n"+
  "} \n"+
  "",
  'dither.frag':
  "#version 100 \n"+
  "precision mediump float; \n"+
  " \n"+
  "uniform sampler2D sampler; \n"+
  "varying vec2 texCoord; \n"+
  " \n"+
  "void main() { \n"+
  "    if (mod(gl_FragCoord.y, 2.0) < 1.0) \n"+
  "        gl_FragColor = vec4(texture2D(sampler, texCoord).xyz, 1); \n"+
  "    else \n"+
  "        gl_FragColor = vec4(.1, .1, .1, 1); \n"+
  "} \n"+
  "",
  'effect.vert':
  "#version 100 \n"+
  " \n"+
  "attribute vec4 vertex; \n"+
  "varying vec2 texCoord; \n"+
  " \n"+
  "void main() { \n"+
  "    gl_Position = vec4(vertex.xy, 0, 1); \n"+
  "    texCoord = vertex.zw; \n"+
  "} \n"+
  "",
  'grayscale.frag':
  "#version 100 \n"+
  "precision mediump float; \n"+
  " \n"+
  "uniform sampler2D sampler; \n"+
  "varying vec2 texCoord; \n"+
  " \n"+
  "void main() { \n"+
  "    vec3 p = texture2D(sampler, texCoord).xyz; \n"+
  "    float x = (p.x + p.y + p.z) / 3.0; \n"+
  "    gl_FragColor = vec4(x, x, x, 1); \n"+
  "} \n"+
  ""
}
