if [ $# -eq 0 ]; then
    echo "usage: $0 <files>"
    exit 1
fi

PADDER=""
echo "// This file was generated by running command"
echo "//     $0 $@"
echo 'shaders = {'
for FILE in "$@"; do
    echo -ne $PADDER
    echo -en "  '$(basename $FILE)':\n"
    cat $FILE | while IFS= read LINE; do
        echo "  \"$LINE \\n\"+";
    done
    echo -n '  ""'
    PADDER=",\n"
done
echo
echo '}'
